00000005!!!!!2020-04-01 09:30:32: ERROR d.f.i.r.j.p.JAXBProviderFactory - marshaller not valid for type com.sun.research.ws.wadl.Application
00000006!!!!!2020-04-01 09:31:33: ERROR d.f.i.r.j.r.a.controller.ClientUser - Invalid command: login
00000007!!!!!2020-04-01 09:32:33: ERROR d.f.i.r.j.r.a.controller.ClientUser - Invalid command: login
00000008!!!!!2020-04-01 09:33:33: ERROR d.f.i.r.j.r.a.controller.ClientUser - Invalid command: login
00000009!!!!!2020-04-01 09:34:33: ERROR d.f.i.r.j.p.DbcKeyExceptionMapper - init exception was caught at system border: invalid init token
00000010!!!!!2020-04-01 09:35:33: ERROR d.f.i.r.j.p.DbcKeyExceptionMapper - init exception was caught at system border: invalid init token
00000011!!!!!2020-04-01 09:36:33: INFO d.f.i.r.p.AbstractProcessor - Processor failed: USER_GET_ONE_ERROR_ID_OR_PASSWORD_WRONG
00000012!!!!!2020-04-01 09:37:33: INFO d.f.i.r.p.AbstractProcessor - Processor failed: PROGRAM_GET_ONE_ERROR_NOT_FOUND
00000013!!!!!2020-04-01 09:38:33: ERROR d.f.i.r.w.CalliopeCompilerWorker - compile calliope2017NoBlue program NEPOprog failed with (COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED, [1/3] Building the NEPOprog.
00000014!!!!!2020-04-01 09:39:33: ERROR d.f.i.r.w.c.ArduinoCompilerWorker - compile nano program FahrenGrundlagenundUltraschallsensor failed with (COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED, /tmp/openrobertaTmp/CNPEY2U3/FahrenGrundlagenundUltraschallsensor/source/FahrenGrundlagenundUltraschallsensor.ino: In function 'void setSpeedLeft(double)':
00000015!!!!!2020-04-01 09:40:33: ERROR d.f.i.r.j.r.a.c.ClientConfiguration - Exception. Error ticket: E-55
00000016!!!!!2020-04-01 09:41:33: ERROR d.f.i.r.persistence.dao.ProgramDao - update was requested, timestamps don't match. Has another user updated the program in the meantime?
00000017!!!!!2020-04-01 09:42:33: ERROR d.f.i.r.r.RobotCommunicator - ROBOT_RC: /pushcmd from a robot arrived, no matching state was found - we return a server error
00000018!!!!!2020-04-01 09:43:33: ERROR d.f.i.r.persistence.dao.ProgramDao - update was requested, timestamps don't match. Has another user updated the program in the meantime?
00000019!!!!!2020-04-01 09:44:33: ERROR d.f.i.r.j.r.r.RobotDownloadProgram - upload error: file 'NEPOprog.hex' to upload to robot not found.
00000020!!!!!2020-04-01 09:45:33: ERROR d.f.i.r.w.c.SenseboxCompilerWorker - compile sensebox program NEPOprog failed with (COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED, /tmp/openrobertaTmp/f2MV0_x3t-O_/NEPOprog/source/NEPOprog.ino: In function 'void loop()':
